Repository TesseractCoding/NeoAlgo, pull requests merged in 2020-12, with the labels that each got.

#753 Affine Cipher Cryptography using Java
  Java/cryptography/AffineCipher.java
  Java/cryptography/README.md
Labels: Java

#1071 Zig Zag in java
  Java/README.md
  Java/cp/Zig_Zag.java
Labels: Hacktoberfest, no-pr-activity

#1157 added cycle detection algorithm in C-Plus-Plus/graphs
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/detect_cycle.cpp
Labels: no-pr-activity

#1234 Added Armstrong Numbers in Javascript
  JavaScript/README.md
  JavaScript/math/ArmstrongNumbers.js
Labels: no-pr-activity

#1223 Armstrong number
  Python/README.md
  Python/math/CheckArmstrongNumber.py
Labels: Hacktoberfest, Python, no-pr-activity

#1274 Added Bilinar_Search.java in search
  Java/README.md
  Java/search/Bilinear_Search.java
Labels: no-pr-activity

#1437 Merge Sort Using recursion In Java in reply to issue (Merge Sort in JavaScript #1427)
  Java/README.md
  Java/sort/MergeSortRecursion.java
Labels: JavaScript

#1448 Unique Binary Tree and Catalan Number Issue #1436
  Python/README.md
  Python/dp/binary_trees_with_n_nodes.py
  Python/math/Catalan_Number.py
Labels: Changes Requested, Reviewed

#1485 Topological Sort added in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/TopologicalSort.cpp
Labels: Reviewed

#1505 Knight's Tour Problem Added under Backtracking
  Python/README.md
  Python/backtracking/Knight's_Tour.py
Labels: under review

#1484 Areas of 2D and 3D figures
  Go/README.md
  Go/math/Areas2D.go
  Go/math/Areas3D.go
Labels: Changes Requested

#1486 Added Topological Sort in Java
  Java/README.md
  Java/graphs/TopologicalSort.java
Labels: Reviewed

#1457 Kth largest/smallest element program in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Kth_largest_element.cpp
  C-Plus-Plus/other/Kth_smallest_element.cpp
Labels: Changes Requested, Reviewed

#1491 Added Vector ds
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Vector.cpp
Labels: Changes Requested, Reviewed

#1433 Added Moore Algorithm in Java->Algorithms issue#1439
  Java/Algorithms/Moore_Algorithm.java
  Java/README.md
  Python/README.md
  Python/other/Moore_Algorithm.py
Labels: Changes Requested, Reviewed

#1454 Added Boyer Moore Majority Vote Algorithm in Js
  JavaScript/Algorithms/BoyerMooreAlgorithm.js
  JavaScript/README.md
Labels: Changes Requested, Reviewed

#1481 Unique_BST.py added under DP Issue-#1455
  Python/README.md
  Python/dp/Unique_BST.py
Labels: under review

#1521 Added Floyd Warshall And Knight Walk
  Python/README.md
  Python/graphs/Bridge_Edge_in_Graph.py
  Python/graphs/Floyd_Warshall_Algorithm.py
  Python/graphs/Knight_Walk.py
Labels: Changes Requested, Reviewed

#1489 Added Cycle Detection in a Directed Graph in Java
  Java/README.md
  Java/graphs/DirectedCycleDetection.java
Labels: Changes Requested, Reviewed

#1431 Radix Sort added in C, C++, Java
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/radix_sort.cpp
  C/README.md
  C/sort/radix_sort.c
  Java/README.md
  Java/sort/RadixSort.java
Labels: Changes Requested, Reviewed, merge conflicts

#1603 Added Bridge edge in Graph in python
  Python/README.md
  Python/graphs/Bridge_Edge_in_Graph.py
Labels: documentation

#1564 Strong Number Using Indirect recursion
  Java/README.md
  Java/math/check_strong_number.java
Labels: Changes Requested, Reviewed

#1600 Added stock span problem
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Stock_span_problem.cpp
Labels: Changes Requested, Reviewed

#1377 Max_subarray_sum(DP).cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Max_subarray_sum(DP).cpp
  C-Plus-Plus/math/check_palindrome.cpp
  C/README.md
  C/ds/Reverse_linked_list.c
  C/search/TernarySearch.c
Labels: C-Plus-Plus, Reviewed, ready-to-merge

#1634 Searching algorithm in go
  Go/README.md
  Go/search/interpolation_search.go
Labels: Changes Requested, Reviewed

#1488 Directed Cycle detection added in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/DirectedCycleDetection.cpp
Labels: Reviewed

#1518 Sidhant prs
  C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp
Labels: Changes Requested

#1531 Added NQueens in Java
  Java/README.md
  Java/cp/NQueens.java
Labels: Changes Requested, Reviewed

#1532 Add Caeser Cipher, Modified Caeser Cipher and Homophonic Cipher
  C-Plus-Plus/cryptography/Caeser_Cipher.cpp
  C-Plus-Plus/cryptography/Homophonic_Cipher.cpp
  C-Plus-Plus/cryptography/Modified_Caeser_Cipher.cpp
Labels: Changes Requested, Reviewed

#1534 Added NQueens in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/NQueens.cpp
Labels: Changes Requested, Reviewed

#1633 vernam cipher implemented
  C-Plus-Plus/README.md
  C-Plus-Plus/cryptography/VernamCipher.cpp
Labels: Changes Requested, Reviewed

#1569 Added Breadth First Search in Python.
  Python/README.md
  Python/graphs/BFS.py
Labels: Changes Requested, Reviewed

#1559 Added Josephus Problem in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Josephus.cpp
Labels: Changes Requested, Reviewed

#1601 Added check for balanced parenthesis
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/Check_for_balanced_parenthesis.cpp
Labels: Changes Requested, Reviewed

#1588 Solved: Count ways to Nth Stair in Java and Python (issue #1455)
  Java/README.md
  Java/cp/Staircase_problem.java
  Python/README.md
  Python/cp/staircase_problem.py
Labels: Reviewed, merge conflicts, ready-to-merge

#1551 #1455 Egg Dropping Problem
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Egg_Dropping.cpp
Labels: Changes Requested, under review

#1570 Added Depth First Search in Python.
  Python/README.md
  Python/graphs/DFS.py
Labels: Changes Requested, Reviewed

#1586 Program to print ancestors of given number of BST
  C-Plus-Plus/ds/ancestors_of_given_number_BST.cpp
Labels: Changes Requested, Reviewed

#1591 Added Matrix-Chain-Multiplication in Python.
  Python/README.md
  Python/dp/Matrix-Chain-Multiplication.py
Labels: Changes Requested, Reviewed

#1635 Add Transposition Cryptography Algorithms: Rail Fence, Simple Columnar, and Simple Columnar with Multiple Rounds
  C-Plus-Plus/README.md
  C-Plus-Plus/cryptography/Rail_fence_Cipher.cpp
  C-Plus-Plus/cryptography/Simple_Columnar_Transposition.cpp
  C-Plus-Plus/cryptography/Simple_Columnar_Transposition_multiple_rounds.cpp
Labels: Changes Requested, Reviewed

#1720 Median in a running stream of integers added
  C-Plus-Plus/README.md
  C-Plus-Plus/heap/Median_in_a_running_stream_of_integers.cpp
Labels: Changes Requested, Reviewed

#1817 Updated Radix Sort to operate on negative numbers
  C-Plus-Plus/sort/radix_sort.cpp
Labels: DWOC
