Repository TesseractCoding/NeoAlgo, pull requests merged in 2021-02, with the labels that each got.

#2017 implemented merge sort for kotlin lang
  Kotlin/Readme.md
  Kotlin/sort/MergeSort/src/MergeSort.kt
Labels: Changes Requested

#2031 program to detect the middle element of a linkedlist in c is added
  C/README.md
  C/ds/middle_element_of_linkedlist.c
Labels: Changes Requested, Reviewed

#2052 Yuvraj 2
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/Infix_to_Postfix.c
Labels: Changes Requested, under review

#2067 Add palindrome
  Python/README.md
  Python/math/Palindrome.py
Labels: Changes Requested, Reviewed

#2068 Postfix Evaluation
  C/README.md
  C/ds/EvaluationOfPostfixExpression.c
Labels: Changes Requested, Reviewed

#2056 Issue #1780 - Letter count #DWOC
  Python/README.md
  Python/cp/LetterCount.py
Labels: Changes Requested, Reviewed

#2034 Ankita Added Diameter Of A BinaryTree Using Java
  Java/Algorithms/Moore_Algorithm.java
  Java/Algorithms/RussianPeasant.java
  Java/Algorithms/kadanes_Java.java
  Java/ds/Diameter_Of_A_BinaryTree.java
  Java/ds/Infix_to_Postfix.java
Labels: Changes Requested, DWOC

#2057 Issue #1780 - VowelsConsonants #DWOC
  Python/README.md
  Python/cp/VowelsConsants.py
Labels: Changes Requested, Reviewed

#2107 Page Replacement Algorithms PR
  Java/Operating-System/allocate.java
  Java/README.md
Labels: DWOC, under review

#2060 Issue#1620 - reverse linked list in golang
  Go/README.md
  Go/ds/singly_linked_list_reversed.go
Labels: Changes Requested, Reviewed, ready-to-merge

#2092 Sleep sort in python
  Python/README.md
  Python/sort/Sleep_sort.py
Labels: Changes Requested, DWOC, Level-2, under review

#2152 Cyclically rotate list clockwise, Issue #2106, #DWOC
  Python/README.md
  Python/cp/Cyclically_rotate.py
Labels: DWOC, Level-1, Reviewed

#2157 AVL tree in python
  Python/README.md
  Python/ds/AVL_Tree.py
Labels: DWOC, Level-3

#2144 Added Sleep Sort in C++ with markdown file.
  C-Plus-Plus/README.md
  C-Plus-Plus/math/README.md
  C-Plus-Plus/other/README.md
  C-Plus-Plus/sort/sleep_sort.cpp
Labels: DWOC, Level-3

#2111 Implementation in Java #1999
  Java/README.md
  Java/cp/Longest_Pallindromicsubstring.java
Labels: DWOC, Reviewed, invalid, plagiarism

#2131 AVL tree in Java
  Java/README.md
  Java/ds/AVL_Tree.java
Labels: DWOC, Level-3, ready-to-merge

#2151 Added jump search algorithm
  Python/README.md
  Python/search/jump_search.py
Labels: Changes Requested, DWOC, Level-1, do not merge yet

#2164 added knapsack fractional in python
  Python/README.md
  Python/dp/Knapsack_fractional.py
Labels: Changes Requested, under review

#2132 feat: Added Bead Sort in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/Bead_Sort.cpp
Labels: Changes Requested, Reviewed

#2093 Add Code for Zero_N_Knapsack
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Zero_N_Knapsack.cpp
  C-Plus-Plus/graphs/BFS1.cpp
Labels: Changes Requested, under review

#2184 Added Bead Sort in C
  C/README.md
  C/sort/beadSort.c
Labels: Changes Requested, Reviewed

#2162 Russian Peasant Algorithm
  C-Plus-Plus/README.md
  C-Plus-Plus/other/RussianPeasantAlgo.cpp
Labels: Changes Requested, Reviewed
