Repository TesseractCoding/NeoAlgo, pull requests merged in 2021-03, with the labels that each got.

#2174 add knapsack fraction problem using greedy appraoch.
  C-Plus-Plus/README.md
  C-Plus-Plus/other/knapsackfraction.cpp
Labels: Changes Requested, ready-to-merge

#2265 🚀[Feat]: Adding Fibonacci Search in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/search/fibonacci_search.cpp
Labels: GSSoC'21, ready-to-merge

#2199 Add Shamir's Secret Sharing cryptographic algorithm in C-Plus-Plus
  C-Plus-Plus/README.md
  C-Plus-Plus/cryptography/Shamir_Secret_Sharing.cpp
Labels: GSSoC'21, Reviewed, ready-to-merge

#2201 Remove Minimum Parantheses to make Valid Parantheses
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/removeMinParantheses.cpp
Labels: GSSoC'21, Reviewed, ready-to-merge

#2213 Make linguist ignore *.ipynb files
  .gitattributes
Labels: GSSoC'21, ready-to-merge

#2231 Optimized N-Queen Problem using JAVA
  Java/README.md
  Java/cp/N_Queens_Problem_Efficient.java
Labels: GSSoC'21, Reviewed, ready-to-merge

#2245 Wave Sort #2228
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/wave_sort.cpp
Labels: GSSoC'21, Reviewed, ready-to-merge

#2276 Added bankers algorithm in C language.
  C/C_Style_guide.md
  C/README.md
  C/operating_system/bankers.c
Labels: GSSoC'21, Reviewed, ready-to-merge

#2313 [CPP][Math/Number Theory] Added modular_exponentiation.cpp & binomial_coefficient_under_modulo.cpp in math section.
  C-Plus-Plus/README.md
  C-Plus-Plus/math/binomial_coefficient_under_modulo.cpp
  C-Plus-Plus/math/modular_exponentiation.cpp
Labels: GSSoC'21, ready-to-merge

#2353 Check Pangram added
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/check_pangram.cpp
Labels: GSSoC'21, Reviewed, ready-to-merge

#2220 Hash Table
  JavaScript/README.md
  JavaScript/ds/Hash.js
Labels: GSSoC'21, ready-to-merge

#2243 Added the solution to check for a binary search tree in Java
  Java/README.md
  Java/ds/CheckBST.java
Labels: GSSoC'21, ready-to-merge

#2291 Added Top K frequent elements under heap section.
  C-Plus-Plus/README.md
  C-Plus-Plus/heap/Top_K_frequent_elements.cpp
Labels: GSSoC'21, ready-to-merge

#2270 Hamming Distance in Bits Manipulation
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Hamming_Distance.cpp
Labels: GSSoC'21, ready-to-merge

#2310 Unbounded knapsack using dynamic programming in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/unbounded_knapsack.cpp
Labels: GSSoC'21, ready-to-merge

#2239 Added divisors of natural number in cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/other/divisors_of_natural_number.cpp
Labels: GSSoC'21, ready-to-merge

#2343 Added code for insertion and deletion to convert one code to another
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/min_ins_del.cpp
Labels: GSSoC'21, ready-to-merge

#2352 largest subarray which contains equal no of 0s and 1s
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
Labels: Changes Requested, GSSoC'21, under review

#2356 ADDED IMPLEMENTATION OF DOUBLY LINKED LIST AND UPDATED README.md of C…
  C/README.md
  C/ds/doubly_linked_list.c
Labels: Changes Requested, GSSoC'21, under review

#2361 Added code for the next greatest element to the right for each element in the array using stack in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/next_greatest_right.cpp
Labels: Changes Requested, GSSoC'21, under review

#2373 The code to find length of the longest palindromic subsequence using dynamic programming in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/longest_palin_subseq.cpp
Labels: GSSoC'21, ready-to-merge

#2378 Added code for K_Closest_Points_to_Origin
  C-Plus-Plus/README.md
  C-Plus-Plus/heap/K_Closest_Points_to_Origin.cpp
Labels: GSSoC'21, Reviewed

#2649 Prime Number maths implemented
  Python/math/prime_number.py
Labels: GSSoC'21, ready-to-merge

#2642 In place merge sort
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/in_place_merge_sort.cpp
Labels: GSSoC'21, ready-to-merge

#2292 Added Two Pointer Method
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/README.md
  C-Plus-Plus/cp/Two_Pointers_Method.cpp
Labels: Changes Requested, GSSoC'21, under review

#2441 Added MinMax Algorithm implementation in Java
  Java/Algorithms/Min_Max_Algorithm_implementation.java
  Java/README.md
Labels: Changes Requested, GSSoC'21

#2705 Added Strassen's Algorithm implementation in Java
  Java/Algorithms/Strassens_Algo_for_Matrix_multiplication.java
  Java/README.md
Labels: GSSoC'21, ready-to-merge

#2602 Luhn's Algorithm in C
  C/README.md
  C/cp/LuhnsAlgo.c
Labels: GSSoC'21, ready-to-merge

#2531 Updates
  Python/README.md
  Python/ds/Palindrome-doublylinkedlist.py
Labels: GSSoC'21, ready-to-merge

#2297 Solution to the Longest Increasing Subsequnce problem using Dynamic Programming in JavaScript
  JavaScript/Algorithms/LongestIncreasingSubsequenceDP.js
  JavaScript/README.md
Labels: GSSoC'21, ready-to-merge

#2232 added_Iterative_Binary_Search
  C/README.md
  C/search/IterativeBinarySearch.c
Labels: GSSoC'21, ready-to-merge

#2499 Adjacent Element Product in C
  C/README.md
  C/cp/Adjacent_Element_Product.c
Labels: GSSoC'21, ready-to-merge

#2594 The Fibonacci series always starts with a 0.
  Python/math/Fibonacci.py
Labels: GSSoC'21, ready-to-merge

#2722 Coin change problem
  Go/README.md
  Go/dp/coin_change_problem.go
Labels: GSSoC'21, ready-to-merge

#2661 Added code for next smallest element to the right using stacks in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/nextSmallestToRight.cpp
Labels: GSSoC'21, Reviewed

#2672 Issue 2662
  Python/math/Fibonacci.py
  Python/math/fibonacci_recursion.py
Labels: GSSoC'21, ready-to-merge

#2427 Added C++ program for krishnamurthy number
  C-Plus-Plus/README.md
  C-Plus-Plus/math/krishnamurthy_number.cpp
Labels: GSSoC'21, ready-to-merge

#2425 Palindrome Partitioning in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Palindrome_Partitioning.cpp
  C-Plus-Plus/dp/README.md
Labels: Changes Requested, GSSoC'21, under review

#2256 Added Shaker Sort in C
  C/README.md
  C/sort/shaker_sort.c
Labels: GSSoC'21, ready-to-merge

#2814 Added code for issue #2750
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/alternate_merging_of_linked_list.cpp
Labels: GSSoC'21, ready-to-merge

#2715 Added K Tree c++ code with detailed explanation under dp section of c-plus-plus
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/K-Tree.cpp
Labels: GSSoC'21, ready-to-merge

#2510 Added Ticket Auction
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/tkt_auction.cpp
Labels: GSSoC'21, Reviewed

#2636 added Number of K-Length Sublists with Average at Least Target.py
  Python/README.md
  Python/cp/Number_of_K-Length_Sublists_with_Average_at_Least _Target.py
Labels: Assigned, GSSoC'21

#2710 Added the code for Bucket Sort in Python
  Python/README.md
  Python/sort/Bucket_sort.py
Labels: Reviewed

#2587 Basic heap implementation
  C-Plus-Plus/README.md
  C-Plus-Plus/heap/heap_implementation.cpp
Labels: GSSoC'21, Reviewed

#2484 Finding_a_pair_of_element.c
  C/README.md
  C/ds/Finding_a_pair_of_element.c
Labels: GSSoC'21, ready-to-merge

#2677 Added the code for Converting decimal number to binary in C++ Problem
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Convert_decimal_to_binary.cpp
Labels: GSSoC'21, Level-1, Reviewed

#2558 Added Neon Number
  C/README.md
  C/math/Neon_number.c
Labels: GSSoC'21, Reviewed

#2586 Linked list Insertion
  JavaScript/README.md
  JavaScript/ds/DynamicLinkedList.js
Labels: GSSoC'21, ready-to-merge

#2498 Job Sequencing to Maximize Profit in Java
  Java/README.md
  Java/dp/JobSequencingToMaximizeProfit.java
Labels: GSSoC'21, ready-to-merge

#2512 Fractional Knapsack in Java
  Java/Greedy_Algorithms/FractionalKnapsack.java
  Java/README.md
Labels: GSSoC'21, ready-to-merge

#2540 Longest common subsequence
  Go/README.md
  Go/dp/longest_common_subsequence.go
Labels: GSSoC'21, Reviewed

#2527 Alleny244 patch 1
  Java/README.md
  Java/ds/SparseMatrices.java
Labels: GSSoC'21, ready-to-merge

#2539 Balanced Brackets in Java
  Java/README.md
  Java/ds/balancedBrackets.java
Labels: GSSoC'21, ready-to-merge

#2883 Previous Greater Element
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/Previous_Greater_Element.cpp
Labels: GSSoC'21, Reviewed

#2700 StackUsingqueueImp
  C/README.md
  C/ds/StackUsingQueue.c
Labels: C, Reviewed

#2530 N-Queens Problem in Javascript
  JavaScript/Backtracking/N-Queens.js
  JavaScript/README.md
Labels: GSSoC'21, ready-to-merge

#2939 Added Sparse Matrix in C
  C/README.md
  C/ds/Sparse_Matrix.c
Labels: GSSoC'21, ready-to-merge

#2874 Update README.md file of Python & C++
  C-Plus-Plus/README.md
  Python/README.md
Labels: GSSoC'21, ready-to-merge

#2944 Added Vernam Cipher in C #2663
  C/README.md
  C/cryptography/Vernam_Cipher.c
Labels: GSSoC'21, Reviewed

#2712 Added Adjacency List in C
  C/README.md
  C/graphs/Adjacency_List.c
Labels: GSSoC'21, ready-to-merge

#2689 Added Sliding Window Technique
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Calculate_max_sum_of_k_consecutive_elements.cpp
Labels: GSSoC'21, ready-to-merge

#2678 Added adjacent element product problem solution
  Java/README.md
  Java/other/AdjacentElementProduct.java
Labels: GSSoC'21, ready-to-merge

#2670 Paths from source to destination added
  Java/README.md
  Java/graphs/Paths_From_Source_To_Destination.java
Labels: GSSoC'21, ready-to-merge

#2650 Added code for Reversing Queue content using Stack in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Reverse_Queue_content_using_Stack.cpp
Labels: GSSoC'21, ready-to-merge

#2660 PR for issue #2154
  Python/README.md
  Python/other/check_valid_parenthesis_string.py
Labels: GSSoC'21, ready-to-merge

#2669 Dynamic Huffman Program Added
  C-Plus-Plus/README.md
  C-Plus-Plus/other/DynamicHuffman.cpp
Labels: GSSoC'21, ready-to-merge

#2953 Smallest element in an array using Stack
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/smallest_element_in_an_array.cpp
Labels: GSSoC'21, ready-to-merge

#3014 Added Prefix Sum Array
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/prefix_sum.cpp
Labels: GSSoC'21, Reviewed

#3017 Added Leaf Nodes in BST in C
  C/README.md
  C/ds/Leaf_Nodes_BST.c
Labels: GSSoC'21, ready-to-merge

#3020 Added BST_Sort in C
  C/README.md
  C/sort/BST_Sort.c
Labels: GSSoC'21, ready-to-merge

#2424 MergeSort implementation in C#
  C-Sharp/README.md
  C-Sharp/sort/MergeSort.cs
Labels: GSSoC'21, under review

#2981 Added Merging Two Sorted Arrays
  Java/README.md
  Java/ds/MergeSortedArrays.java
Labels: GSSoC'21, Reviewed

#3041 Added a source code for finding Lexicographically largest palindrome subsequence
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Lexicographyically_largest_palindrome_subsequence.cpp
Labels: Changes Requested, GSSoC'21, Reviewed

#3058 Added Strong Number program
  Python/README.md
  Python/math/Strong_Number.py
Labels: GSSoC'21, ready-to-merge

#2747 Sieve eratosthenes
  Go/README.md
  Go/math/sieve_of_eratosthenes.go
Labels: Reviewed

#2713 Added wiggle sort in C-Plus-Plus
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/wiggle_sort.cpp
Labels: Reviewed

#2904 deletion in linked list
  JavaScript/ds/DynamicLinkedList.js
Labels: GSSoC'21, ready-to-merge

#3088 stack using linked list
  JavaScript/README.md
  JavaScript/ds/StackLinkedList.js
Labels: GSSoC'21, ready-to-merge

#3026 Added Trie Implementation Using Java Hashmap Closes #2968
  Java/README.md
  Java/ds/Trie_with_Hashmap.java
Labels: GSSoC'21, ready-to-merge

#2693 Added remove spaces from a string
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/remove_spaces_from_a_string.cpp
Labels: GSSoC'21, ready-to-merge

#2511 Reverse words in a given string using java
  Java/README.md
  Java/cp/Reverse_words_in_String.java
Labels: GSSoC'21, Reviewed

#3259 Anagram String Code
  Java/README.md
  Java/cp/Anagram.java
Labels: GSSoC'21, ready-to-merge

#3021 Covering other possible cases in the program
  C-Plus-Plus/stack/Check_for_balanced_parenthesis.cpp
Labels: GSSoC'21, ready-to-merge

#2987 Created InfixtoPrefix program in Java
  Java/README.md
  Java/other/InfixtoPrefix.java
Labels: GSSoC'21, ready-to-merge

#2989 Added check if a number is power of 2
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Check_whether_a_number_is_power_of_2.cpp
Labels: GSSoC'21, ready-to-merge

#3104 Added code for Conversion of Binary to Decimal
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
Labels: Changes Requested, GSSoC'21, Reviewed

#3191 Added Hash Table in C
  C/README.md
  C/ds/Hash_Table.c
Labels: GSSoC'21, ready-to-merge

#3195 Added Jump Search in C
  C/README.md
  C/search/JumpSearch.c
Labels: GSSoC'21, ready-to-merge

#2916 resolved issue #2894 i.e. min swap to sort array.
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/MinSwapToSortArray.cpp
Labels: GSSoC'21, ready-to-merge

#2877 Added Round Robin Scheduling Algorithm with Gantt chart
  C/README.md
  C/operating_system/Round_Robin_Scheduling.c
Labels: GSSoC'21, ready-to-merge

#2259 Added code for LCA of a tree using binary lifting in c++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/LowestCommonAncestor_in_Tree.cpp
Labels: Changes Requested, GSSoC'21, under review

#3053 Implemented Infix to Postfix in Java
  Java/README.md
  Java/other/InfixToPostfix.java
Labels: GSSoC'21, ready-to-merge

#3037 Added Sine function algorithm
  Python/README.md
  Python/math/Sine_Function.py
Labels: GSSoC'21, ready-to-merge

#3059 Find all permutation of a string using recursion
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/recursion_string_permutation.cpp
Labels: GSSoC'21, ready-to-merge

#2899 Depth First Search Python
  Python/search/dfs.py
Labels: GSSoC'21, ready-to-merge

#2990 Added code for Sum of Digit
  Java/README.md
  Java/math/SumOfDigit.java
Labels: Changes Requested, GSSoC'21, Reviewed

#3116 Tower of Hanoi in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Tower_Of_Hanoi.cpp
Labels: GSSoC'21

#3016 Tarunyadav148
  C-Plus-Plus/README.md
  C-Plus-Plus/math/magic_number.cpp
Labels: GSSoC'21, Reviewed

#2675 Issue 2556
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Detet_Cycle_In_LinkedList.cpp
Labels: GSSoC'21, Reviewed

#3050 Neon number added
  C-Plus-Plus/README.md
  C-Plus-Plus/math/neon_number.cpp
Labels: GSSoC'21, ready-to-merge

#3338 Added Optimised_Bubble_Sort.py
  Python/README.md
  Python/sort/Optimized_Bubble_Sort.py
Labels: GSSoC'21, ready-to-merge

#3323 Sublist Search in CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/search/sublist_Search.cpp
Labels: GSSoC'21, ready-to-merge

#2825 Code for Issue 2566
  Python/README.md
  Python/graphs/Rotten_Oranges.py
Labels: GSSoC'21, ready-to-merge

#3347 Concatenation of two strings in C .Issue:#3011
  C/README.md
  C/other/concatenate_two_strings.c
Labels: GSSoC'21, ready-to-merge

#3295 Fibonacci search
  Java/README.md
  Java/search/Fibonacci_search.java
Labels: GSSoC'21, ready-to-merge

#3312 Added Painting Fence Algorithm in Python
  Python/README.md
  Python/cp/Paint_Fence.py
Labels: GSSoC'21, ready-to-merge

#2284 Adding HeapSort in C
  C/README.md
  C/sort/HeapSort.c
Labels: Changes Requested, GSSoC'21, under review

#3286 Added Comb Sort implementation in Java
  Java/README.md
  Java/sort/CombSort_implementation.java
Labels: GSSoC'21, ready-to-merge

#2978 Added code for generating BST from it's Preorder Traversal #2605
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/BST_from_Preorder_Traversal.cpp
Labels: GSSoC'21, ready-to-merge

#3357 Remove Duplicate in a Linked List Without using Extra Space
  Java/README.md
  Java/ds/RemDupInLLWithoutExtraSpace.java
Labels: GSSoC'21, ready-to-merge

#3112 added bit manipulation
  C-Plus-Plus/Bit--Manipulation/Brian_Kernighan's_Algorithm.cpp
  C-Plus-Plus/Bit--Manipulation/Check_kth_bit_is_set_or_not.cpp
  C-Plus-Plus/Bit--Manipulation/Count_no_of_set_bits.cpp
  C-Plus-Plus/Bit--Manipulation/One_odd_occuring.cpp
  C-Plus-Plus/Bit--Manipulation/Power_Set_Using_Bitwise.cpp
  C-Plus-Plus/Bit--Manipulation/Power_of_2.cpp
  C-Plus-Plus/Bit--Manipulation/Swap_even_and_odd_bits.cpp
  C-Plus-Plus/Bit--Manipulation/Two_odd_occuring.cpp
  C-Plus-Plus/README.md
Labels: GSSoC'21, Level-3, Reviewed

#3063 Issue 2910
  C-Plus-Plus/README.md
  C-Plus-Plus/search/Manacher's_Algorithm.cpp
  C-Plus-Plus/search/README.md
  C-Plus-Plus/search/Unbounded_Binary_Search.cpp
Labels: GSSoC'21, ready-to-merge

#3400 Added Painting Fence Code for C++/CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Paint_Fence.cpp
Labels: GSSoC'21, ready-to-merge

#3385 Comb sort c++
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/comb_sort.cpp
Labels: GSSoC'21, ready-to-merge

#2699 Added code for Rotten Oranges Problem in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Rotten_Oranges.cpp
Labels: GSSoC'21, Reviewed

#2197 Merging two Linked List using c
  C/README.md
  C/ds/Merging_two_Linked_List.c
Labels: GSSoC'21, ready-to-merge

#2319 Algorithm for finding Peak element added
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Peak_element.cpp
  C-Plus-Plus/cp/README.md
Labels: GSSoC'21, under review

#2859 Added Radix Sort in C# language
  C-Sharp/sort/RadixSort.cs
Labels: GSSoC'21, ready-to-merge

#2858 Code for FirstFit BestFit WorstFit
  Java/README.md
  Java/dp/MemoryAllocations.java
Labels: GSSoC'21, ready-to-merge

#2857 Code for Sparse Matrix in Java
  Java/ds/SparseMatrices.java
Labels: GSSoC'21, ready-to-merge

#2840 Refactor queue implementation in python
  Python/ds/Queue.py
Labels: GSSoC'21, ready-to-merge

#2887 Three way merge sort in c
  C/README.md
  C/sort/three_way_merge_sort.c
Labels: GSSoC'21, ready-to-merge

#2822 Implementation of Stack using queues in Python
  Python/README.md
  Python/ds/Implementation_of_Stack_using_queues.py
Labels: GSSoC'21, ready-to-merge

#2619 added code and explanation for reverse lookup in 1D array
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Reverse_Lookup_in_1D_array.cpp
Labels: GSSoC'21, Reviewed

#3442 Added Arctan Algorithm
  Python/README.md
  Python/math/Arctan.py
Labels: GSSoC'21, ready-to-merge

#3441 Added Three Sum problem in java
  Java/README.md
  Java/other/three_Sum_problem.java
Labels: GSSoC'21, ready-to-merge

#3424 Reverse linked list
  JavaScript/ds/DynamicLinkedList.js
Labels: GSSoC'21, ready-to-merge

#3412 process id input mismatch
  Java/Operating-System/CPU_Scheduling_FCFS.java
Labels: GSSoC'21, ready-to-merge

#3408 Issue 2509
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/LevelOrderTraversal.cpp
Labels: GSSoC'21, ready-to-merge

#3052 Added Three way merge sort in c++
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/three_way_merge_sort.cpp
Labels: GSSoC'21, ready-to-merge

#3036 Added number of subsets with given diff in dp in c++
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/subsets_with_given_diff.cpp
Labels: GSSoC'21, ready-to-merge

#3047 Added BST Sort in C-Plus-Plus
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/BST_Sort.cpp
Labels: Reviewed

#3221 Added Maximum of All Subarrays of Size K in Java
  Java/README.md
  Java/cp/MaximumEachSubarray.java
Labels: Reviewed

#3481 Reverse String using Stack in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Reverse_string_using_stack.cpp
Labels: Changes Requested, GSSoC'21, Reviewed

#3476 Implementation of min heap in C (issue #2749)
  C/README.md
  C/ds/minHeap.c
Labels: GSSoC'21, ready-to-merge

#3186 Added OPEN_SOURCE_EVENTS.md
  OPEN_SOURCE_EVENTS.md
Labels: GSSoC'21, ready-to-merge

#3513 Modified Readme File
  README.md
Labels: GSSoC'21, ready-to-merge

#3316 Added code to print longest common subsequence
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Print_Longest_Common_Subsequence.cpp
Labels: gssoc21, plagiarism-review, under review

#3226 Added Maximum of Minimum for Every Window Size in Java
  Java/README.md
  Java/cp/MaximumOfMinimumSubarrays.java
Labels: Reviewed, merge conflicts

#2852 Lucky Numbers
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Lucky_Numbers.cpp
Labels: gssoc21, under review

#3309 Added code for sort color
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Sort_Color.cpp
Labels: Level-2, gssoc21

#3079 Update CheckBST.java
  Java/ds/CheckBST.java
Labels: Level2, gssoc21

#3089 Added code for Array Manipulaiton in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Array_Manipulation.cpp
Labels: Level3, gssoc21

#3190 Added Arranging elements of array to form biggest possible number
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Arranging_elements_of_array_to_form_biggestno.cpp
Labels: Level3, gssoc21

#3235 Added Longest Substring with K Distinct Characters in Java
  Java/README.md
  Java/cp/LongestSubstringDistinctChar.java
Labels: Level3, gssoc21

#3243 Added Minimum Window Substring in Java
  Java/README.md
  Java/cp/MinimumWindowSubstring.java
Labels: Level3, gssoc21

#3326 Added the code for deletion of elements from the LinkedList using Java
  Java/README.md
  Java/ds/DeleteElementLL.java
Labels: Reviewed, gssoc21

#3507 Added Paint Fence Algorithm in Java
  Java/README.md
  Java/cp/Paint_Fence.java
Labels: Level3, gssoc21, ready-to-merge

#3379 Jump Game
  Java/README.md
  Java/cp/Jump_Game.java
Labels: Level3, gssoc21, ready-to-merge
