Repository TesseractCoding/NeoAlgo, pull requests merged in 2021-01, with the labels that each got.

#1556 Boyer-Moore_Majority_Voting_algorithm is added
  C/README.md
  C/cp/BoyerMooreVote.c
Labels: Changes Requested, Reviewed

#1652 BST Validation in Python
  Python/README.md
  Python/ds/Binary-Search-Tree-Validation.py
Labels: Changes Requested, Reviewed

#1670 Added SVM Code to Machine Learning
  Python/README.md
  Python/ml/Support_Vector_Machine.ipynb
Labels: Changes Requested, Reviewed

#1761 Created Circular Queue in C
  C/README.md
  C/ds/circularqueue.c
Labels: Changes Requested, Reviewed

#1825 Added Tarjan's Algo and modified the required changes
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/Tarjan's_Algoirthm.cpp
Labels: Changes Requested, Reviewed

#1833 Added Maximum Subarray Sum (Constant Space) in CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Max_subarray_sum_constant_space(DP).cpp
Labels: Changes Requested, Reviewed

#1755 Created ShellSort in Java
  Java/README.md
  Java/sort/ShellSort.java
Labels: Reviewed

#1595 Depth Of Tree
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/Depth_of_tree.cpp
Labels: Changes Requested, Reviewed

#1819 Added bankers algorithm in java
  Java/Operating-System/banker.java
  Java/README.md
Labels: Changes Requested, Reviewed

#1456 Catalan Number Series
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/number_of_binary_trees.cpp
Labels: Changes Requested, Reviewed

#1787 Add Burrows Wheeler Transform in python
  Python/README.md
  Python/cryptography/Burrows_Wheeler_transform.py
Labels: Changes Requested, under review

#1775 Lucas Theorem implementation
  Python/README.md
  Python/math/Lucas_Theorem.py
  Python/math/README.md
Labels: DWOC

#1708 Created PriorityQueueEg.java
  Java/README.md
  Java/ds/PriorityQueueEg.java
Labels: Changes Requested, DWOC, Reviewed

#1942 Created the program to find GCD of two numbers
  Java/README.md
  Java/other/FindGCDOfTwoNo.java
Labels: DWOC

#1946 Added Articulation points in an Undirected Graph
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/Articulation_points.cpp
Labels: DWOC

#1748 Merge Sort in JavaScript
  JavaScript/README.md
  JavaScript/sort/MergeSort.js
Labels: Changes Requested, Reviewed

#1941 Threaded Binary Tree code added.
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/ThreadedBinaryTree.cpp
Labels: Changes Requested, Reviewed

#1829 Insertion sort for Kotlin added
  Kotlin/Readme.md
  Kotlin/sort/InsertionSort/src/InsertionSort.kt
Labels: DWOC

#1964 Add Inorder Traversal
  C/README.md
  C/ds/Inorder.c
Labels: DWOC

#1943 Created String Palindrome program in Java
  Java/README.md
  Java/other/Palindrome.java
Labels: Changes Requested

#1928 Program to convert BST to Greater Sum Tree
  C-Plus-Plus/ds/BST_to_Greater_Sum_Tree.cpp
Labels: Changes Requested, under review

#1934 Benjamin Bulb in java
  C-Plus-Plus/ds/CircularQueue.cpp
  Java/other/BenjaminBulb.java
Labels: Changes Requested, Reviewed

#1808 Added counting_sort.cpp which implements Counting Sort for integers for DWOC 2020-21
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/counting_sort.cpp
Labels: Changes Requested, DWOC, Reviewed

#1966 Added Matrix Script in Python
  Miscellaneous/HackerRank/MatrixScript.py
  Miscellaneous/HackerRank/README.md
Labels: Changes Requested, Reviewed

#2011 Added Exponent Search and updated README.md
  C-Plus-Plus/README.md
  C-Plus-Plus/search/exponential_search.cpp
Labels: DWOC

#2014 Plot_graph.py added to Other Algorithms
  Python/README.md
  Python/other/Plot_Graph.py
Labels: under review

#2022 Sleep Sort in Java
  Java/README.md
  Java/sort/SleepSort.java
Labels: DWOC, Level-2

#2028 Added linked_list_middle_element.cpp which detects the middle element…
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/linked_list_middle_element.cpp
Labels: Changes Requested, Reviewed

#2024 Reverse a string #1999
  Java/README.md
  Java/cp/ReverseString.java
Labels: Changes Requested, Reviewed

#2025 Memory Allocation in Operating Systems in Java
  Java/Operating-System/alloc.java
  Java/README.md
Labels: Changes Requested, Reviewed

#2023 Radixsort in go
  Go/README.md
  Go/sort/radixSort.go
Labels: DWOC, do not merge yet, under review

#1949 countingSort.c submission for DWOC
  C/README.md
  C/sort/countingSort.c
Labels: Changes Requested

#1788 Implemented Counting Sort in Java
  Java/README.md
  Java/sort/CountingSort.java
Labels: Changes Requested, DWOC, Level-1

#1854 Evaluate string expression BODMAS (stack) code added
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/string_expression_evaluation_bodmas.cpp
Labels: Changes Requested, no-updates, under review

#2020 Add stack using linked list
  C/README.md
  C/ds/StackImplementationWithLinkedList.c
Labels: Reviewed, ready-to-merge

#2015 Implemented Radix Sort in Kotlin
  Kotlin/Readme.md
  Kotlin/sort/RadixSort/src/RadixSort.kt
Labels: Changes Requested

#2066 Angastrom
  JavaScript/Algorithms/Armstrong.js
  JavaScript/README.md
Labels: Changes Requested, Reviewed

#2061 Added Logically Weighted Regression
  .DS_Store
  Python/README.md
  Python/ml/Logically_weighted_regression.py
Labels: Changes Requested, Reviewed
