Repository TesseractCoding/NeoAlgo, pull requests merged in 2021-04, with the labels that each got.

#2898 feat: Added Arithmetic slices problem in C++ (Issue #2717)
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Arithmetic_Slices.cpp
Labels: Reviewed, gssoc21

#4811 Implemented recursive binary search in Go
  Go/README.md
  Go/search/Binary_Recursive_Search/BinarySearchRecursive.go
Labels: Level2, gssoc21

#4441 Minimize_Amplitude_After_K_Removals.py
  Python/README.md
  Python/cp/Minimize_Amplitude_After_K_Removals.py
Labels: Changes Requested, gssoc21, under review

#4797 Iterative Merge Sort in C
  C/README.md
  C/sort/Iterative_Merge_Sort.c
Labels: GSSoC'21, Level3, Reviewed, gssoc21

#4819 added level order traversal(issue #4757)
  Java/README.md
  Java/ds/LevelOrderTraversalRecursion.java
Labels: gssoc21, under review

#4825 Added gnome sort in Python
  Python/README.md
  Python/sort/gnome_sort.py
Labels: gssoc21, plagiarism-review, under review

#4595 Plucking Flowers
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Plucking_Flowers.cpp
Labels: GSSoC'21, Reviewed, gssoc21

#4909 Added Palindrome Partitions
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Print_Palindrome_Partitions.cpp
Labels: gssoc21, under review

#4659 Largest Kth Element (DC Problem)
  C-Sharp/README.md
  C-Sharp/other/Largest_Kth_Element.cs
Labels: gssoc21, under review

#4937 Added Playfair cipher in golang
  Go/README.md
  Go/cryptography/PlayFair_Cipher/playfaircipher.go
Labels: gssoc21, under review

#4698 Tiling Problem 2xN in python
  Python/README.md
  Python/dp/tiling_problem_2xN.py
Labels: gssoc21, under review

#4393 Print the first non repeating character in a running stream of characters
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/first_non_repeating_character.cpp
Labels: Changes Requested, gssoc21, under review

#4833 Remove Zero Sum Consecutive Nodes from Linked List
  Python/README.md
  Python/ds/consecutive_sum_is_zero.py
Labels: gssoc21, under review

#4962 Implemented Mystery Number in Go
  Go/README.md
  Go/math/Mystery_Number/Mystery_Number.go
Labels: Level2, gssoc21

#4898 Detection of cycle in a Linked List using C++
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/detectionOfCycle_likedList.cpp
Labels: gssoc21, under review

#3644 FIXED #3043 - Array: Inverse of an array
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/inverse_of_an_array.cpp
Labels: gssoc21, under review

#4390 Job Scheduling algorithm - Greedy Problem in JAVA
  Java/Greedy_Algorithms/Job_Scheduling.java
  Java/README.md
Labels: Changes Requested, gssoc21, under review

#4900 Issue#4899 Code Added and README.md Updated
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Group_Anagrams.cpp
  Python/sort/Wiggle_sort.py
Labels: gssoc21, under review

#4970 Union of two arrays
  Python/README.md
  Python/other/Union_of_two_arrays.py
Labels: Reviewed, gssoc21

#4634 Pshivesh8
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Searching_in_BST.cpp
Labels: Level3, Reviewed, gssoc21

#4648 Tiling Problem 2XN
  C/README.md
  C/dp/tiling_problem.c
Labels: gssoc21, under review

#4613 Added flight of stairs in js
  JavaScript/README.md
  JavaScript/dp/flightOfStairs.js
Labels: Changes Requested, gssoc21, under review

#5013 Double ended queue java
  Java/README.md
  Java/ds/DEQueue.java
Labels: Changes Requested, gssoc21, under review

#4992 Inversion Vector of a Singly Linked List
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/inversion_vector.cpp
Labels: Changes Requested, gssoc21, under review

#4184 First Negative Integer In Every Window Of Size K in JavaScript
  JavaScript/README.md
  JavaScript/cp/FirstNegativeIntegerInEveryWindowOfSizeK.js
Labels: Changes Requested, gssoc21, under review

#4228 Count Anagrams in JavaScript
  JavaScript/README.md
  JavaScript/cp/CountAnagrams.js
Labels: Changes Requested, gssoc21, under review

#4173 Sliding Window Maximum in JavaScript
  JavaScript/README.md
  JavaScript/cp/SlidingWindowMaximum.js
Labels: Changes Requested, gssoc21, under review

#4161 Added the solution to Reverse Alternate k nodes in a linked list in Java
  Java/README.md
  Java/ds/Reverse_alternate_k_Nodes.java
Labels: Changes Requested, gssoc21, under review

#4851 Check whether a number is a Strong Number or not in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Strong_Number.cpp
Labels: GSSoC'21, gssoc21, under review

#4724 Permutation of string added
  C/README.md
  C/other/Permutation_of_string.c
Labels: gssoc21, under review

#5052 Added Insert Usernames in Database in CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/other/insert_usernames_in_database.cpp
Labels: gssoc21

#3271 algorithm added issue no.: #2933
  C-Plus-Plus/README.md
  C-Plus-Plus/other/job_sheduling_with_deadlines.cpp
Labels: Changes Requested, gssoc21, under review

#3383 Adding file and updated readme issue-3337
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Check_for_Binary_search_tree.cpp
Labels: gssoc21, under review

#3772 union of unsorted array
  Java/README.md
  Java/other/UnionUnsortedArray.java
Labels: gssoc21, under review

#4123 Finding prime number in range.
  Java/README.md
  Java/cp/Prime_range.java
Labels: gssoc21, under review

#4059 adding hashtable chaining in c
  C/README.md
  C/ds/Hashtable_chaining.c
Labels: Changes Requested, gssoc21, under review

#4337 Rod Cutting in JAVA[ #2489 - Fixed ]
  Java/README.md
  Java/dp/Rod_Cutting.java
Labels: Changes Requested, gssoc21, under review

#4817 Added the Construction of binary tree using inorder and preorder unde…
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Construct_binary_tree_using_inorder_and_preorder.cpp
Labels: gssoc21, under review

#4711 Reconstruct Original Digits from English
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/ReconstructOriginalDigitsFromEnglish.cpp
Labels: gssoc21, under review

#4363 Articulation Point in JAVA[ #2491 - Fixed ]
  Java/README.md
  Java/graphs/Articulation_Point.java
Labels: Changes Requested, gssoc21, under review

#4339 Added the code file
  Julia/README.md
  Julia/cp/RainwaterTrapping.jl
Labels: gssoc21

#5071 Added code for finding maximum number formed from the given array of 2-digit numbers
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/maxNumber.cpp
Labels: C-Plus-Plus, Level2, gssoc21

#4525 Union and intersection
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Union_and_Intersection_of_arrays.cpp
Labels: gssoc21, under review

#3904 Added the program for Node to Root Path in a Binary Tree
  Java/README.md
  Java/ds/NodetoRootPath.java
Labels: Changes Requested, gssoc21, under review

#4980 Kth smallest element in an array
  C-Plus-Plus/README.md
  C-Plus-Plus/heap/KthSmallestElement.cpp
Labels: Changes Requested, gssoc21, under review

#4467 Recursive preorder of binary search tree in javascript
  JavaScript/README.md
  JavaScript/ds/recursive_preorder.js
Labels: Changes Requested, Reviewed, gssoc21, under review

#5074 BipartiteCheck - Fix for PR #4882
  Java/README.md
  Java/graphs/BipartiteCheck.java
Labels: Changes Requested, gssoc21, merge conflicts, under review

#4925 Add Binary Search Tree to Python
  Python/README.md
  Python/ds/BinarySearchTree.py
Labels: Changes Requested, gssoc21, under review

#4947 Add Exponential Search In kotlin
  Kotlin/Readme.md
  Kotlin/search/ExponentialSearch.kt
Labels: gssoc21, under review

#4950 Add Palindrome Number in Kotlin
  Kotlin/Maths/PalindromeNumber.kt
  Kotlin/Readme.md
Labels: gssoc21, under review

#4738 Pair star
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Pair-Star.cpp
Labels: gssoc21, under review

#4640 IMPLEMENTED ASCENDING PRIORITY QUEUE IN C
  C/README.md
  C/ds/AscendingPQ.c
Labels: gssoc21, under review

#4697 Pair of nodes in the BST which sum to S
  C-Plus-Plus/README.md
  C-Plus-Plus/search/Pair Of Nodes In The BST Which Sum To S.cpp
Labels: gssoc21, under review

#4447 Added Next permutation in Python
  Python/README.md
  Python/cp/Next_Permutation.py
Labels: gssoc21, under review

#3757 Added the code for LCA of BST in Java
  Java/README.md
  Java/ds/LCAofaBST.java
Labels: gssoc21, under review

#5018 Sorting an array of 0's and 1's
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
Labels: Changes Requested, gssoc21, under review

#5084 Added code for postfix to prefix conversion in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/postfix_to_prefix.cpp
Labels: Changes Requested, gssoc21, under review

#5012 Transpose of a Square Matrix using C++
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Transpose_Of_Square_Matrix.cpp
Labels: Reviewed, gssoc21

#5126 adding matrix transpose in python
  Python/README.md
  Python/math/Matrix_transpose.py
Labels: Changes Requested, gssoc21, merge conflicts, under review

#5286 Updated Readme
  README.md
Labels: Assigned, Level1, documentation, gssoc21

#5075 Median of arrays in c
  C/README.md
  C/cp/Median_of_two_sorted_arrays.c
Labels: Changes Requested, gssoc21, under review

#5243 kReverse in LinkedList using C++
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/kReverse_LinkedList.cpp
Labels: Level2, gssoc21

#5194 Adding Python/other/minimize_the_jump.py
  Python/README.md
  Python/other/minimize_the_jump.py
Labels: Changes Requested, gssoc21, under review

#4716 GCD of two Numbers in Javascript
  JavaScript/README.md
  JavaScript/math/gcd_of_two_no.js
Labels: gssoc21, under review

#4657 Palindrome Checker in Javascript
  JavaScript/README.md
  JavaScript/math/Palindrome_checker.js
Labels: gssoc21, under review

#5206 Implemented Post-order traversal in Go
  Go/README.md
  Go/ds/binary_tree/post_order_traversal/Post_Order_Traversal.go
Labels: gssoc21, under review

#5256 Implemented Pre-Order traversal of a tree in Go
  Go/README.md
  Go/ds/binary_tree/pre_order_traversal/Pre_Order_Traversal.go
Labels: Level2, gssoc21

#4910 Added code for Pair programmers productivity problem in Java
  Java/README.md
  Java/other/Pair_programmers_productivity_problem.java
Labels: Changes Requested, gssoc21, under review

#5017 add code for Product of maximum in first array and minimum in second
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Product_of_the_maximum_element_and_the_minimum_element_in_two_consecutive_arrays.cpp
Labels: Changes Requested, gssoc21, under review

#5043 Circular queue java
  Java/README.md
  Java/ds/CircularQueue.java
Labels: gssoc21, under review

#4758 Added Queue using linkedlist
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Queue_all_operations_using_linkedlist.cpp
Labels: Changes Requested, gssoc21, under review

#5198 Loop detection in a Linked List using Python
  Python/README.md
  Python/ds/loop_detection_in_LL.py
Labels: Changes Requested, gssoc21, under review

#5252 Adding the algo to calculate subsets of Array in Julia
  Julia/README.md
  Julia/cp/subsetsOfArray.jl
Labels: Changes Requested, gssoc21, under review

#5170 Added Code for Count Inversions in C
  C/README.md
  C/sort/Count_Inversions.c
Labels: Changes Requested, gssoc21, under review

#5156 Busy Man Problem in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/busy_man.cpp
Labels: Changes Requested, gssoc21, under review

#5157 Minimum circles to be removed in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/min_circles_to_be_removed.cpp
Labels: Changes Requested, gssoc21, under review

#5257 3 Cycle
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/3Cycle.cpp
Labels: Changes Requested, gssoc21, under review

#5370 Automorphic Number in Julia
  Julia/README.md
  Julia/math/automorphic_number.jl
Labels: Julia, gssoc21

#5182 Check whether a number is a Perfect Number or not in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Perfect_Number.cpp
Labels: Changes Requested, gssoc21, under review

#5250 Activity Selection in python
  Python/README.md
  Python/cp/activity_selection.py
Labels: Changes Requested, gssoc21, under review

#5121 Find repeating and missing number in array using CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/other/repeated_missing.cpp
Labels: Changes Requested, gssoc21, under review

#5304 Kadane's Algorithm
  JavaScript/Algorithms/kadane's_algo.js
  JavaScript/README.md
Labels: Changes Requested, gssoc21, under review

#5218 Bit Operation In Kotlin
  Kotlin/BitManipulation/BasicBitOperations.kt
  Kotlin/Readme.md
Labels: Changes Requested, gssoc21, under review

#5251 Inversion count problem using merge sort in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/InversionCountProblem.cpp
Labels: Changes Requested, gssoc21, under review

#5295 Matrix addition in java
  Java/README.md
  Java/math/Matrix_addition.java
Labels: Changes Requested, gssoc21, under review

#5255 Minimum sum partition in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Minimum_sum_partition.cpp
Labels: Changes Requested, gssoc21, under review

#5279 Palindrome Number
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Palindrome_number.cpp
Labels: gssoc21, under review

#5472 Modifications to Insertion Sort code in C++
  C-Plus-Plus/sort/insertion.cpp
Labels: Level2

#5473 Implemented Factorial using Dynamic Programming in Go
  Go/README.md
  Go/dp/factorial/factorial.go
Labels: Level2

#5465 Longest Decreasing Subsequence in Julia | GSSOC'21 | DP
  Julia/README.md
  Julia/dp/length_longest_decreasing_subsequence.jl
Labels: Level2

#5291 Fibonacci Search
  JavaScript/README.md
  JavaScript/search/FibonacciSearch.js
Labels: gssoc21, under review

#5476 Unique number
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Unique_number.cpp
Labels: gssoc21, under review

#5467 Sum of Digits of a Number in Python
  Python/README.md
  Python/math/sum_of_digits.py
Labels: Level2, gssoc21

#5446 Coin
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Maximum_ways_Coin_change_problem.cpp
Labels: gssoc21, under review

#5325 Count the number of subset with a given difference
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Count_subset_given_difference.cpp
Labels: gssoc21, under review

#5326 new file: Python/other/merge_interval.py
  Python/README.md
  Python/other/merge_interval.py
Labels: gssoc21, under review

#4503 DFS implementation of Graph in C#
  C-Sharp/README.md
  C-Sharp/graphs/DFS.cs
Labels: Changes Requested, gssoc21, under review

#5434 Add Floyd Warshall Algorithm Using Dynamic Approach In Java To NeoAlgo
  Java/README.md
  Java/dp/FloydWarshallAlgorithm.java
Labels: gssoc21, under review

#5153 Infix to Prefix Converter in JavaScript
  JavaScript/README.md
  JavaScript/ds/infixtoprefix.js
Labels: Changes Requested, gssoc21, under review

#5159 Fibonnaci Number in Kotlin
  Kotlin/Maths/FibonacciNumber.kt
  Kotlin/Readme.md
Labels: Changes Requested, gssoc21, under review

#5411 Automorphic Number in DART
  Dart/README.md
  Dart/maths/automorphic_number.dart
Labels: gssoc21, under review

#5413 add GitHub action to label DART code related issues
  .github/labeler.yml
Labels: gssoc21, under review

#5421 Sum of digits dart
  Dart/README.md
  Dart/maths/SumOfDigits.dart
Labels: Changes Requested, gssoc21, under review

#5439 Matrix multiplication in javascript
  JavaScript/README.md
  JavaScript/math/Matrix_multiplication.js
Labels: GSSoC'21, bug

#5462 Implementation of RRT Algorithm
  Python/Pathfinding/2D_RRT.py
  Python/README.md
Labels: gssoc21, under review

#5483 Fibonacci Search in Dart
  Dart/README.md
  Dart/search/FibonacciSearch.dart
Labels: Changes Requested, gssoc21

#5076 Two pointer Algorithm using java
  Java/Algorithms/Two_pointer_Algorithm.java
  Java/README.md
Labels: Changes Requested, gssoc21, under review

#5582 Modified rail fence cipher
  C-Plus-Plus/cryptography/Rail_fence_Cipher.cpp
Labels: Level1, gssoc21

#5301 Matrix transpose in javascript
  JavaScript/README.md
  JavaScript/math/Matrix_transpose.js
Labels: Changes Requested, gssoc21, under review

#5062 Toggle k-th bit of a number
  C-Plus-Plus/Bit--Manipulation/togglebit.cpp
  C-Plus-Plus/README.md
Labels: Changes Requested, gssoc21, under review

#5449 Stack using arrays java
  Java/README.md
  Java/ds/StackUsingArrays.java
Labels: Changes Requested, gssoc21, under review

#5531 Interpolation Search in Dart
  Dart/README.md
  Dart/search/InterpolationSearch.dart
Labels: Changes Requested, gssoc21, under review

#5391 Rain Water Trapping Problem in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/rain_water_trapping.cpp
Labels: Changes Requested, gssoc21, under review

#5597 Reverse a String in JavaScript
  JavaScript/README.md
  JavaScript/cp/ReverseString.js
Labels: Changes Requested, gssoc21, under review

#5557 Matrix Addition in C++ restructured
  C-Plus-Plus/math/matrix_addition.cpp
Labels: No-Issue, gssoc21

#5558 Modified Matrix Addition in C
  C/math/matrix_addition.c
Labels: No-Issue, gssoc21

#5010 Three sum
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Three_Sum.cpp
Labels: Level2, gssoc21

#5578 Dividing Tasks to Student in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Dividing_tasks.cpp
Labels: Changes Requested, gssoc21, under review

#5152 Infix to Postfix Converter in JavaScript
  JavaScript/README.md
  JavaScript/ds/infixtopostfix.js
Labels: Changes Requested, gssoc21, under review

#5654 Print first letter of every word in the string
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Print_first_letter_of_every_word_in_the_string.cpp
Labels: gssoc21, under review

#5519 Staircase using DP
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Staircase.cpp
Labels: gssoc21, under review

#4876 Added Floyd Warshall Algorithm in Java
  Java/README.md
  Java/graphs/Floyd_Warshall_Algorithm.java
Labels: Changes Requested, gssoc21, under review

#5674 Sieve of Eratosthenes program in Java
  Java/Algorithms/Sieve_of_Eratosthenes.java
  Java/README.md
Labels: Changes Requested, gssoc21, medium

#5353 Reverse a Linked List in groups
  Python/README.md
  Reverse_in_groups_LL.py
Labels: do not merge yet, gssoc21, plagiarism-review, under review

#5680 Small fixes in Automorphic number code in dart.
  Dart/maths/automorphic_number.dart
Labels: enhancement, gssoc21, under review

#5729 List sort on the basis of tuple
  Python/sort/ListTuplesort.py
  Python/sort/README.md
Labels: Changes Requested, gssoc21, under review

#5414 Added Max topology Short
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Max_Topology_short.cpp
Labels: Changes Requested, gssoc21, under review

#5655 Longest Decreasing Sequence in Python
  Python/README.md
  Python/dp/length_common_decreasing_subsequence.py
Labels: gssoc21, under review

#5653 Golomb Sequence in Python
  Python/README.md
  Python/dp/golomb_sequence.py
Labels: Changes Requested, gssoc21, under review

#5496 Boruvka’s Algorithm in cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/Boruvka_algorithm_for_finding_MST.cpp
Labels: Changes Requested, gssoc21, under review

#5587 Transpose of a Matrix in C
  C/README.md
  C/math/matrix_transpose.c
Labels: Changes Requested, gssoc21, under review

#5677 Egg Dropping problem in Java
  Java/README.md
  Java/dp/EggDroppingProblem.java
Labels: Changes Requested, gssoc21, under review

#4776 Lucky Numbers ( Number Theory) in Python
  Python/README.md
  Python/math/Lucky_Numbers.py
Labels: Changes Requested, gssoc21, under review

#5403 All Unique Permutations in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/all_unique_permutation.cpp
Labels: gssoc21, merge conflicts, under review

#5399 Adjacent Difference Algorithm
  C-Plus-Plus/README.md
  C-Plus-Plus/adjacent.cpp
Labels: Changes Requested, gssoc21, under review

#5586 Matrix Subtraction in C
  C/README.md
  C/math/matrix_subtraction.c
Labels: Changes Requested, gssoc21, under review

#5619 Binary Exponentiation in dart
  Dart/README.md
  Dart/maths/Binary_Exponentiation.dart
Labels: Changes Requested, gssoc21, under review

#5450 Combinational Sum without repeating the array value using Recursion
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
Labels: Changes Requested, gssoc21, under review

#5642 Queue using stacks in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Queue_using_Stacks.cpp
Labels: Changes Requested, gssoc21, under review

#5647 Rotate the Matrix 90 degree to right
  C-Plus-Plus/README.md
  C-Plus-Plus/math/Matrix_rotation_90degree.cpp
Labels: Changes Requested, gssoc21, under review

#5623 Wiggle sort in C
  C/README.md
  C/sort/Wiggle_sort.c
Labels: Changes Requested, gssoc21, under review

#5408 Create Ackermann function (dart)
  Dart/README.md
  Dart/maths/Ackermann_function.dart
Labels: Changes Requested, gssoc21, under review

#5775 Top view of binary tree in CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/top_view_binary_tree.cpp
Labels: Changes Requested, gssoc21, under review

#5755 Kth missing positive number
  C-Plus-Plus/README.md
  C-Plus-Plus/other/kth_missing.cpp
Labels: Changes Requested, do not merge yet, gssoc21, question, under review

#5781 Decimal to binary conversion in Dart
  Dart/README.md
  Dart/maths/DecimalToBinary.dart
Labels: Changes Requested, gssoc21, under review

#5786 Connecting Dots in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/connecting_dots.cpp
Labels: Changes Requested, gssoc21, under review

#5739 Staircase search using c
  C/README.md
  C/search/Staircase_Search.c
Labels: Changes Requested, gssoc21, under review

#5667 Count of digits in python
  Python/README.md
  Python/math/count_of_digits.py
Labels: do not merge yet, gssoc21, question

#5645 Reverse a number in c++
  C-Plus-Plus/README.md
  C-Plus-Plus/math/reverse_a_number.cpp
Labels: do not merge yet, gssoc21, question

#5644 Reverse of a number in python
  Python/README.md
  Python/math/reverse_a_number.py
Labels: do not merge yet, gssoc21, question
