Repository TesseractCoding/NeoAlgo, pull requests merged in 2021-05, with the labels that each got.

#6652 Counting Sort in Dart
  Dart/README.md
  Dart/sort/Counting_Sort.dart
Labels: Changes Requested, gssoc21, under review

#6671 Deletion in Circular Singly Linked List in JavaScript
  JavaScript/ds/CircularSinglyLinkedList.js
Labels: gssoc21, under review

#6775 Binary to Decimal Number in C
  C/README.md
  C/math/binary_to_decimal.c
Labels: Changes Requested, gssoc21, under review

#6694 Best fit in python
  Python/README.md
  Python/ds/Bestfit.py
Labels: Changes Requested, gssoc21, merge conflicts, under review

#6772 Roots of Quadratic equation in C
  C/README.md
  C/math/Quadratic_Equation.c
Labels: Changes Requested, gssoc21, under review

#6699 Refactor : Maximum in array
  C-Plus-Plus/cp/Maximum_In_Array.cpp
Labels: gssoc21

#6793 Added Power Of Two in Kotlin
  Kotlin/BitManipulation/PowerOfTwo.kt
  Kotlin/Readme.md
Labels: Changes Requested, gssoc21, under review

#6646 Added code for Sum of Root To Leaf Binary Numbers
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/RootToLeafSum.cpp
Labels: Changes Requested, gssoc21, under review

#6704 Colouring Binary Tree in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/colouring_binary_tree.cpp
Labels: Level3, gssoc21

#6767 Linear Probing in Hashing using Python
  Python/README.md
  Python/ds/Linear_Probing_In_Hashing.py
Labels: Changes Requested, gssoc21, under review

#6178 Ones and Zeroes in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Ones_and_Zeroes.cpp
Labels: Changes Requested, gssoc21, under review

#6546 Reverse first k elements in a queue in Python
  Python/README.md
  Python/ds/Reverse_First_K_elements_of_Queue.py
Labels: Changes Requested, gssoc21, merge conflicts, under review

#6807 next nth palindrome in python
  Python/README.md
  Python/math/Next_Palindrome.py
Labels: Changes Requested, gssoc21, under review

#6904 Added code for sum of 2 large numbers represented as strings in c++.
  C-Plus-Plus/README.md
  C-Plus-Plus/math/SumOf_TwoLarge_numbers_represented_as_strings.cpp
Labels: gssoc21, invalid

#6732 Auto Key Cipher Algorithm in C
  C/README.md
  C/cryptography/AutoKey_Cipher.c
Labels: Changes Requested, gssoc21, under review

#6730 Play Fair Cipher Algorithm in Cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/cryptography/PlayFair_Cipher.cpp
Labels: Changes Requested, gssoc21, under review

#6514 Postfix to Infix Conversion in C
  C/README.md
  C/ds/postfixToInfix.c
Labels: gssoc21, under review

#6542 Wave array in Python
  Python/README.md
  Python/other/Wave_Array.py
Labels: Changes Requested, gssoc21, under review

#6791 FCFS algorithm in C
  C/README.md
  C/operating_system/first_come_first_serve_algorithm.c
Labels: Changes Requested, gssoc21, under review

#5868 Merge two sorted arrays without using extra space
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/merge_without_extra_space.cpp
Labels: gssoc21, under review

#6997 Tic Tac Toe Game in Python
  Python/README.md
  Python/backtracking/Tic_Tac_Toe.py
Labels: Level2, gssoc21

#6154 Maximize consecutive average integer pair in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Maxm_consecutive_avgint_pairs.cpp
Labels: Changes Requested, gssoc21, under review

#6943 Merge sort in Julia
  Julia/README.md
  Julia/sort/merge_sort.jl
Labels: Changes Requested, gssoc21, under review

#6668 Fold a linked list in Java
  Java/README.md
  Java/ds/Fold A Linked List.java
Labels: Changes Requested, gssoc21, under review

#7085 Maze Generation Visualiser
  Python/README.md
  Python/backtracking/Maze-Generation-Visualiser.py
Labels: Level2, gssoc21

#6924 Total subtrees with total nodes sum equal to x in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/total_subtrees.cpp
Labels: Level2, gssoc21

#6936 Added Code for Largest Number from elements of the Array
  C-Plus-Plus/README.md
  C-Plus-Plus/other/LargestNumber.cpp
Labels: Level2, gssoc21

#7043 Pancake sort description added
  Resources/Pancake_sort.md
Labels: Level0, gssoc21

#7091 refactor
  C-Plus-Plus/Bit--Manipulation/togglebit.cpp
  C-Plus-Plus/README.md
Labels: Level0, gssoc21

#6902 Adjacent elements Product in python
  Python/README.md
  Python/cp/adjacent_elements_product.py
Labels: Changes Requested, gssoc21, merge conflicts, under review

#7086 Three sum Problem
  Python/README.md
  Python/search/three_sum_problem.py
Labels: Changes Requested, gssoc21, under review

#7143 Sleep sort description added
  Resources/Sleep_sort.md
Labels: Level1, gssoc21

#7010 Maximum Pairwise Product In An Array
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/maximum_pairwise_product.cpp
Labels: Changes Requested, gssoc21, under review

#7130 Sliding Window Technique in Java
  Java/README.md
  Java/cp/slding_window_technique.java
Labels: gssoc21, merge conflicts, ready-to-merge

#6707 Next larger element tree using cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Next_Larger_Element-tree_using_CPP.cpp
Labels: Changes Requested, gssoc21, under review

#7071 Rod cutting problem in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Rod_cutting_problem.cpp
Labels: Changes Requested, gssoc21, under review

#7084 Iterative inorder traversal in javascript
  JavaScript/README.md
  JavaScript/ds/Iterative_inorder.js
Labels: gssoc21, merge conflicts, ready-to-merge

#7111 Largest BST in binary tree in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/largest_bst_in_btree.cpp
Labels: gssoc21, merge conflicts, ready-to-merge

#7152 String permutations in Dart
  Dart/README.md
  Dart/dp/StringPermutations.dart
Labels: Changes Requested, gssoc21, under review

#7155 Iterative postorder traversal in javascript
  JavaScript/README.md
  JavaScript/ds/Iterative_postorder.js
Labels: gssoc21, merge conflicts, ready-to-merge

#7156 Iterative preorder traversal in javascript
  JavaScript/README.md
  JavaScript/ds/Iterative_preorder.js
Labels: gssoc21, merge conflicts, ready-to-merge

#7159 Painting fence problem in java
  Java/README.md
  Java/dp/Painting_fence.java
Labels: Changes Requested, gssoc21, question, under review

#7161 Painting fence problem in javascript
  JavaScript/README.md
  JavaScript/dp/Painting_fence.js
Labels: Changes Requested, gssoc21, under review

#7178 8 Puzzle Problem using A* Algorithm
  Python/README.md
  Python/search/8_Puzzle_Problem_using_A_star_Algorithm.py
Labels: Changes Requested, gssoc21, under review

#7176 8 Puzzle Problem using BFS
  Python/README.md
  Python/search/8_Puzzle_Problem_using_BFS.py
Labels: Changes Requested, gssoc21, under review

#7230 Modified Largest_rect_area_under_histogram.cpp
  C-Plus-Plus/stack/Largest_rect_area_under_histogram.cpp
Labels: Level0, gssoc21

#7124 XOR Linked List
  C/README.md
  C/ds/XOR.c
Labels: Changes Requested, gssoc21, under review

#6492 Unbounded binary search in python
  Python/README.md
  Python/search/unbounded_binary_search.py
Labels: Changes Requested, gssoc21, under review

#7257 Minimum Depth Binary Tree in Java
  Java/README.md
  Java/other/MinimumDepthBT.java
Labels: Level1, gssoc21

#7239 Minimum cost to construct temple in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/min_cost_to_construct_temple.cpp
Labels: Changes Requested, gssoc21, under review

#7040 Diffie Helman Key Exchange
  Python/README.md
  Python/cryptography/Diffie_Helman_Protocol.py
Labels: Changes Requested, gssoc21, under review

#7301 worst fit in javascript
  JavaScript/README.md
  JavaScript/ds/worstfit.js
Labels: Changes Requested, gssoc21, under review

#7300 bestfit in javascript
  JavaScript/README.md
  JavaScript/ds/bestfit.js
Labels: Changes Requested, gssoc21, under review

#7241 XOR Cipher in java
  Java/README.md
  Java/cryptography/XORCipher.java
Labels: Changes Requested, gssoc21, under review

#7282 Array product except self | JAVA
  Java/README.md
  Java/other/ArrayProductExceptSelf.java
Labels: Changes Requested, gssoc21, under review

#7371 Trapping Rain Water 2D Java Implementation
  Java/README.md
  Java/cp/Trapping_rain_water_2D.java
Labels: gssoc21

#7325 Coin Tower - DP
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/coinTower.cpp
Labels: Level2, gssoc21

#7330 House Robber (DP) Python
  Python/README.md
  Python/dp/House_Robber.py
Labels: gssoc21, under review

#7307 Count articles
  Python/README.md
  Python/other/Count_Articles.py
Labels: gssoc21

#7328 Max matrix chain multiplication
  C-Plus-Plus/README.md
  C-Plus-Plus/dp/Max_MatrixChain_Multiplication.cpp
Labels: gssoc21, under review

#7290 Connecting dots graphs using cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Next_Larger_Element-tree_using_CPP.cpp
  C-Plus-Plus/graphs/Connecting _Dots-Graphs_using_cpp.cpp
Labels: Changes Requested, gssoc21, under review

#7319 Side Views of The binary tree
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Side_Views_of_Binary_tree.cpp
Labels: gssoc21

#7418 Added car fueling using greedy approach in CPP
  C-Plus-Plus/README.md
  C-Plus-Plus/other/CarFueling.cpp
Labels: Level2, gssoc21

#7412 Lazy propagation segment tree
  C-Plus-Plus/README.md
  C-Plus-Plus/other/Lazy_Propagation_in_Segment_Tree.cpp
Labels: gssoc21

#7354 Ugly number dart
  Dart/README.md
  Dart/maths/UglyNumber.dart
Labels: gssoc21, merge conflicts

#7387 Solar Radiation Prediction-ML
  Python/README.md
  Python/ml/Solar_Radiation_Prediction.ipynb
Labels: gssoc21, merge conflicts

#7416 Added Lomuto Partitition in java
  Java/README.md
  Java/sort/LomutoPartition.java
Labels: gssoc21

#7317 Added Tim Sort Implementation in Python 3
  Python/README.md
  Python/sort/README.md
  Python/sort/TimSort.py
Labels: gssoc21

#7398 Count the total number of vertices with more children than its parent in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/total_more_child_vertices_than_parent.cpp
Labels: Changes Requested, gssoc21, merge conflicts, under review

#7344 Bfs rotten oranges code
  Java/README.md
  Java/cp/BFS_RottenOranges.java
Labels: Changes Requested, gssoc21, under review

#7409 Finding equilibrium point in the array in Python
  Python/README.md
  Python/other/equilibrium_point_in_array.py
Labels: Changes Requested, gssoc21, under review

#7417 Cycle detection using BFS in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/graphs/checkCycle_bfs.cpp
Labels: Changes Requested, gssoc21, under review

#7464 Crossword Puzzle Java Implementation
  Java/README.md
  Java/cp/Crossword_puzzle.java
Labels: Changes Requested, gssoc21, under review

#7334 Added bitonic subarray #7322
  C/README.md
  C/cp/Bitonic_subarray.c
Labels: Changes Requested, gssoc21, under review

#6512 Relative Sort Array in cpp
  C-Plus-Plus/README.md
  C-Plus-Plus/sort/Relative_Sort_Array.cpp
Labels: Changes Requested, gssoc21, under review

#7118 Search target element in Rotated Sorted Array
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
Labels: Changes Requested, gssoc21, merge conflicts, under review

#7453 Corrected link in README.md by renaming file
  Java/README.md
  Java/ds/foldALinkedList.java
Labels: Changes Requested, gssoc21, under review

#7406 Find first and last positions of an element in a sorted array in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/Find_first_and_last_positions_of_an_element_in_a_sorted_array.cpp
Labels: Changes Requested, gssoc21, under review

#7316 Create BSTtoMinHeap
  C-Plus-Plus/ds/BSTtoMinHeap.cpp
Labels: Changes Requested, gssoc21, under review

#6746 priority queue in python
  Python/README.md
  Python/ds/priority_queue.py
Labels: Changes Requested, gssoc21, under review

#7394 Construction of binary tree from inorder and preorder traversal in C++
  C-Plus-Plus/README.md
  C-Plus-Plus/ds/BinaryTreeFromInorderAndPreorder.cpp
Labels: Changes Requested, gssoc21, merge conflicts, under review

#7451 Added equal sum partition problem in Java
  Java/README.md
  Java/dp/equalSumPartition.java
Labels: PR:On-Hold, gssoc21, under review

#7471 Added code for next ssmallest element to the right in Java
  Java/README.md
  Java/cp/NextSmallestToRight.java
Labels: PR:On-Hold, gssoc21, under review

#7478 Changed code completely for next greater element to improve time and space complexity to linear
  Java/cp/Next_Greater_Element.java
Labels: gssoc21

#7475 Code for next greater element to the left in Java using Stack class
  Java/README.md
  Java/cp/nextGreaterElementLeft.java
Labels: Level1, gssoc21

#7472 Code for next smallest element to the left in Java
  Java/README.md
  Java/cp/nextSmallestToLeft.java
Labels: gssoc21

#7491 Added cpp implementation of two stacks using single array
  C-Plus-Plus/README.md
  C-Plus-Plus/stack/two_stacks_using_single_array.cpp
Labels: gssoc21, under review

#7506 Find Index of 0 to be replaced with 1 to get longest continuous sequence of 1s in a binary array
  C-Plus-Plus/README.md
  C-Plus-Plus/cp/Continuous_Seq.cpp
Labels: gssoc21, under review
